// Parses the EverythingBox app repo's C++ headers into typed TS data modules, so the
// site's systems and emulator lists cannot drift from the application itself.
//
// Run manually after the app's catalog changes:  npm run gen
// The OUTPUT is committed, so the site build never needs the app repo present.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const APP = process.env.EB_APP_REPO ?? 'C:/Users/cubma/Project Goliath';

function parseSystems() {
  const src = readFileSync(join(APP, 'native/src/core/SystemCatalog.h'), 'utf8');
  const body = src.slice(src.indexOf('static const QList<GameSystem> list = {'));
  // { "id", "Name", { "ext", … }, { "core", … }[, "externalEmulator"] },
  const re =
    /\{\s*"([a-z0-9_]+)"\s*,\s*"([^"]+)"\s*,\s*\{([^}]*)\}\s*,\s*\{([^}]*)\}\s*(?:,\s*"([a-z0-9_]+)"\s*)?\}/gs;
  const out = [];
  for (const m of body.matchAll(re)) {
    out.push({
      id: m[1],
      name: m[2],
      extensions: [...m[3].matchAll(/"([^"]+)"/g)].map((x) => x[1]),
      cores: [...m[4].matchAll(/"([^"]+)"/g)].map((x) => x[1]),
      externalEmulator: m[5] ?? '',
    });
  }
  return out;
}

function parseEmulators() {
  const src = readFileSync(join(APP, 'native/src/core/EmulatorRegistry.h'), 'utf8');
  const body = src.slice(src.indexOf('static const QList<ExternalEmulator> list = {'));
  // Each entry opens with id, displayName, then argument templates. fullscreenArgs and
  // windowedArgs may be QString() rather than a literal, so match the id/name pair loosely
  // and take the first non-API https literal that follows as the homepage. Requiring that
  // homepage is what distinguishes a top-level entry from a nested binary-path list.
  const re = /QStringLiteral\("([a-z0-9_]+)"\),\s*QStringLiteral\("([^"]+)"\),/g;
  const seen = new Set();
  const out = [];
  for (const m of body.matchAll(re)) {
    if (seen.has(m[1])) continue;
    const rest = body.slice(m.index, m.index + 1200);
    const hp = rest.match(/QStringLiteral\("(https:\/\/(?!api\.github|git\.ryujinx)[^"]+)"\)/);
    if (!hp) continue;
    seen.add(m[1]);
    out.push({ id: m[1], name: m[2], homepage: hp[1] });
  }
  return out;
}

const banner =
  '// GENERATED by tools/gen-catalog.mjs from the EverythingBox app repo. Do not edit by hand.\n';

const systems = parseSystems();
const emulators = parseEmulators();

if (systems.length < 60) throw new Error(`only parsed ${systems.length} systems — parser is broken`);
if (emulators.length < 14)
  throw new Error(`only parsed ${emulators.length} emulators — parser is broken`);

writeFileSync(
  'src/data/systems.ts',
  `${banner}import type { GameSystem } from './types';\n\nexport const systems: GameSystem[] = ${JSON.stringify(systems, null, 2)};\n`,
);
writeFileSync(
  'src/data/emulators.ts',
  `${banner}import type { Emulator } from './types';\n\nexport const emulators: Emulator[] = ${JSON.stringify(emulators, null, 2)};\n`,
);

console.log(`wrote ${systems.length} systems, ${emulators.length} emulators`);
