// GENERATED by tools/gen-catalog.mjs from the EverythingBox app repo. Do not edit by hand.
import type { Emulator } from './types';

export const emulators: Emulator[] = [
  {
    "id": "dolphin",
    "name": "Dolphin",
    "homepage": "https://dolphin-emu.org/download/"
  },
  {
    "id": "azahar",
    "name": "Azahar (3DS)",
    "homepage": "https://azahar-emu.org/"
  },
  {
    "id": "melonds",
    "name": "melonDS",
    "homepage": "https://melonds.kuribo64.net/"
  },
  {
    "id": "cemu",
    "name": "Cemu",
    "homepage": "https://cemu.info/"
  },
  {
    "id": "ryujinx",
    "name": "Ryujinx (Ryubing)",
    "homepage": "https://ryujinx.app/"
  },
  {
    "id": "ppsspp",
    "name": "PPSSPP",
    "homepage": "https://www.ppsspp.org/download/"
  },
  {
    "id": "vita3k",
    "name": "Vita3K",
    "homepage": "https://vita3k.org/"
  },
  {
    "id": "rpcs3",
    "name": "RPCS3",
    "homepage": "https://rpcs3.net/download"
  },
  {
    "id": "duckstation",
    "name": "DuckStation",
    "homepage": "https://www.duckstation.org/"
  },
  {
    "id": "pcsx2",
    "name": "PCSX2",
    "homepage": "https://pcsx2.net/downloads/"
  },
  {
    "id": "flycast",
    "name": "Flycast",
    "homepage": "https://github.com/flyinghead/flycast/releases"
  },
  {
    "id": "xemu",
    "name": "xemu",
    "homepage": "https://xemu.app/"
  },
  {
    "id": "xenia",
    "name": "Xenia (Canary)",
    "homepage": "https://xenia.jp/"
  },
  {
    "id": "bigpemu",
    "name": "BigPEmu",
    "homepage": "https://www.richwhitehouse.com/jaguar/index.php?content=download"
  },
  {
    "id": "teknoparrot",
    "name": "TeknoParrot",
    "homepage": "https://teknoparrot.com/"
  }
];
