// GENERATED by tools/gen-catalog.mjs from the EverythingBox app repo. Do not edit by hand.
import type { MediaKind } from './types';

export const mediaKinds: MediaKind[] = [
  {
    "type": "movie",
    "name": "Movies"
  },
  {
    "type": "series",
    "name": "TV Shows"
  },
  {
    "type": "game",
    "name": "Games"
  },
  {
    "type": "album",
    "name": "Music"
  },
  {
    "type": "book",
    "name": "Books"
  },
  {
    "type": "audiobook",
    "name": "Audiobooks"
  },
  {
    "type": "comic",
    "name": "Comics"
  },
  {
    "type": "manga",
    "name": "Manga"
  }
];
