// GENERATED by tools/gen-catalog.mjs from the EverythingBox app repo. Do not edit by hand.
import type { GameSystem } from './types';

export const systems: GameSystem[] = [
  {
    "id": "gba",
    "name": "Game Boy Advance",
    "extensions": [
      "gba"
    ],
    "cores": [
      "mgba",
      "vbam",
      "gpsp"
    ],
    "externalEmulator": ""
  },
  {
    "id": "gb",
    "name": "Game Boy / Color",
    "extensions": [
      "gb",
      "gbc",
      "sgb",
      "dmg"
    ],
    "cores": [
      "gambatte",
      "mgba",
      "sameboy"
    ],
    "externalEmulator": ""
  },
  {
    "id": "nes",
    "name": "NES / Famicom",
    "extensions": [
      "nes",
      "fds",
      "unif",
      "unf"
    ],
    "cores": [
      "fceumm",
      "nestopia"
    ],
    "externalEmulator": ""
  },
  {
    "id": "snes",
    "name": "SNES / Super Famicom",
    "extensions": [
      "sfc",
      "smc",
      "bs",
      "st"
    ],
    "cores": [
      "snes9x",
      "bsnes_mercury_balanced"
    ],
    "externalEmulator": ""
  },
  {
    "id": "genesis",
    "name": "Genesis / Mega Drive / SMS / GG",
    "extensions": [
      "md",
      "gen",
      "smd",
      "sms",
      "gg"
    ],
    "cores": [
      "genesis_plus_gx",
      "picodrive"
    ],
    "externalEmulator": ""
  },
  {
    "id": "n64",
    "name": "Nintendo 64",
    "extensions": [
      "n64",
      "z64",
      "v64",
      "ndd"
    ],
    "cores": [
      "mupen64plus_next",
      "parallel_n64"
    ],
    "externalEmulator": ""
  },
  {
    "id": "psx",
    "name": "PlayStation",
    "extensions": [
      "cue",
      "chd",
      "pbp",
      "m3u",
      "ccd",
      "exe"
    ],
    "cores": [
      "swanstation",
      "mednafen_psx_hw",
      "pcsx_rearmed"
    ],
    "externalEmulator": "duckstation"
  },
  {
    "id": "saturn",
    "name": "Sega Saturn",
    "extensions": [
      "cue",
      "chd",
      "ccd",
      "m3u",
      "iso"
    ],
    "cores": [
      "mednafen_saturn",
      "kronos"
    ],
    "externalEmulator": ""
  },
  {
    "id": "pce",
    "name": "PC Engine / TurboGrafx-16",
    "extensions": [
      "pce",
      "sgx"
    ],
    "cores": [
      "mednafen_pce",
      "mednafen_pce_fast"
    ],
    "externalEmulator": ""
  },
  {
    "id": "ws",
    "name": "WonderSwan",
    "extensions": [
      "ws",
      "wsc"
    ],
    "cores": [
      "mednafen_wswan"
    ],
    "externalEmulator": ""
  },
  {
    "id": "virtualboy",
    "name": "Virtual Boy",
    "extensions": [
      "vb"
    ],
    "cores": [
      "mednafen_vb"
    ],
    "externalEmulator": ""
  },
  {
    "id": "a2600",
    "name": "Atari 2600",
    "extensions": [
      "a26"
    ],
    "cores": [
      "stella"
    ],
    "externalEmulator": ""
  },
  {
    "id": "a5200",
    "name": "Atari 5200",
    "extensions": [
      "a52"
    ],
    "cores": [
      "a5200"
    ],
    "externalEmulator": ""
  },
  {
    "id": "a7800",
    "name": "Atari 7800",
    "extensions": [
      "a78"
    ],
    "cores": [
      "prosystem"
    ],
    "externalEmulator": ""
  },
  {
    "id": "lynx",
    "name": "Atari Lynx",
    "extensions": [
      "lnx"
    ],
    "cores": [
      "handy",
      "mednafen_lynx"
    ],
    "externalEmulator": ""
  },
  {
    "id": "ngp",
    "name": "Neo Geo Pocket / Color",
    "extensions": [
      "ngp",
      "ngc",
      "ngpc"
    ],
    "cores": [
      "mednafen_ngp"
    ],
    "externalEmulator": ""
  },
  {
    "id": "sg1000",
    "name": "Sega SG-1000",
    "extensions": [
      "sg"
    ],
    "cores": [
      "genesis_plus_gx",
      "bluemsx"
    ],
    "externalEmulator": ""
  },
  {
    "id": "coleco",
    "name": "ColecoVision",
    "extensions": [
      "col"
    ],
    "cores": [
      "gearcoleco",
      "bluemsx"
    ],
    "externalEmulator": ""
  },
  {
    "id": "vectrex",
    "name": "Vectrex",
    "extensions": [
      "vec"
    ],
    "cores": [
      "vecx"
    ],
    "externalEmulator": ""
  },
  {
    "id": "intellivision",
    "name": "Intellivision",
    "extensions": [
      "int"
    ],
    "cores": [
      "freeintv"
    ],
    "externalEmulator": ""
  },
  {
    "id": "odyssey2",
    "name": "Magnavox Odyssey 2",
    "extensions": [
      "o2"
    ],
    "cores": [
      "o2em"
    ],
    "externalEmulator": ""
  },
  {
    "id": "channelf",
    "name": "Fairchild Channel F",
    "extensions": [
      "chf"
    ],
    "cores": [
      "freechaf"
    ],
    "externalEmulator": ""
  },
  {
    "id": "amiga",
    "name": "Commodore Amiga",
    "extensions": [
      "adf",
      "adz",
      "hdf",
      "uae",
      "dms"
    ],
    "cores": [
      "puae",
      "puae2021"
    ],
    "externalEmulator": ""
  },
  {
    "id": "atarist",
    "name": "Atari ST",
    "extensions": [
      "msa",
      "stx",
      "dim"
    ],
    "cores": [
      "hatari"
    ],
    "externalEmulator": ""
  },
  {
    "id": "pc98",
    "name": "NEC PC-9801",
    "extensions": [
      "d98",
      "fdi",
      "hdi",
      "98d"
    ],
    "cores": [
      "np2kai"
    ],
    "externalEmulator": ""
  },
  {
    "id": "x1",
    "name": "Sharp X1",
    "extensions": [
      "dx1",
      "2d",
      "2hd"
    ],
    "cores": [
      "x1"
    ],
    "externalEmulator": ""
  },
  {
    "id": "zxspectrum",
    "name": "Sinclair ZX Spectrum",
    "extensions": [
      "tzx",
      "z80",
      "szx",
      "rzx",
      "scl",
      "trd",
      "sna"
    ],
    "cores": [
      "fuse"
    ],
    "externalEmulator": ""
  },
  {
    "id": "c64",
    "name": "Commodore 64",
    "extensions": [
      "d64",
      "t64",
      "prg",
      "crt",
      "g64",
      "x64",
      "p00"
    ],
    "cores": [
      "vice_x64",
      "vice_x64sc"
    ],
    "externalEmulator": ""
  },
  {
    "id": "msdos",
    "name": "MS-DOS",
    "extensions": [
      "dosz",
      "com",
      "bat",
      "conf"
    ],
    "cores": [
      "dosbox_pure",
      "dosbox_core"
    ],
    "externalEmulator": ""
  },
  {
    "id": "vic20",
    "name": "Commodore VIC-20",
    "extensions": [
      "20",
      "40",
      "60",
      "a0",
      "b0"
    ],
    "cores": [
      "vice_xvic"
    ],
    "externalEmulator": ""
  },
  {
    "id": "atari800",
    "name": "Atari 800",
    "extensions": [
      "atr",
      "atx",
      "car",
      "cas"
    ],
    "cores": [
      "atari800"
    ],
    "externalEmulator": ""
  },
  {
    "id": "apple2",
    "name": "Apple II",
    "extensions": [
      "woz",
      "do",
      "po",
      "2mg",
      "nib",
      "dsk"
    ],
    "cores": [
      "applewin"
    ],
    "externalEmulator": ""
  },
  {
    "id": "amstradcpc",
    "name": "Amstrad CPC",
    "extensions": [
      "cdt",
      "cpr"
    ],
    "cores": [
      "cap32",
      "crocods"
    ],
    "externalEmulator": ""
  },
  {
    "id": "tic80",
    "name": "TIC-80 (fantasy)",
    "extensions": [
      "tic"
    ],
    "cores": [
      "tic80"
    ],
    "externalEmulator": ""
  },
  {
    "id": "uzebox",
    "name": "Uzebox",
    "extensions": [
      "uze"
    ],
    "cores": [
      "uzem"
    ],
    "externalEmulator": ""
  },
  {
    "id": "pokemini",
    "name": "Pokemon Mini",
    "extensions": [
      "min"
    ],
    "cores": [
      "pokemini"
    ],
    "externalEmulator": ""
  },
  {
    "id": "supervision",
    "name": "Watara Supervision",
    "extensions": [
      "sv"
    ],
    "cores": [
      "potator"
    ],
    "externalEmulator": ""
  },
  {
    "id": "gameandwatch",
    "name": "Nintendo Game & Watch",
    "extensions": [
      "mgw"
    ],
    "cores": [
      "gw"
    ],
    "externalEmulator": ""
  },
  {
    "id": "neogeo",
    "name": "Neo Geo",
    "extensions": [
      "neo"
    ],
    "cores": [
      "geolith",
      "fbneo"
    ],
    "externalEmulator": ""
  },
  {
    "id": "32x",
    "name": "Sega 32X",
    "extensions": [
      "32x"
    ],
    "cores": [
      "picodrive",
      "genesis_plus_gx"
    ],
    "externalEmulator": ""
  },
  {
    "id": "daphne",
    "name": "Daphne (Laserdisc)",
    "extensions": [
      "daphne"
    ],
    "cores": [
      "dirksimple"
    ],
    "externalEmulator": ""
  },
  {
    "id": "segacd",
    "name": "Sega CD / Mega-CD",
    "extensions": [],
    "cores": [
      "genesis_plus_gx",
      "picodrive"
    ],
    "externalEmulator": ""
  },
  {
    "id": "segacd32x",
    "name": "Sega CD 32X",
    "extensions": [],
    "cores": [
      "picodrive"
    ],
    "externalEmulator": ""
  },
  {
    "id": "pcecd",
    "name": "PC Engine CD / TurboGrafx-CD",
    "extensions": [],
    "cores": [
      "mednafen_pce",
      "mednafen_pce_fast"
    ],
    "externalEmulator": ""
  },
  {
    "id": "pcfx",
    "name": "NEC PC-FX",
    "extensions": [],
    "cores": [
      "mednafen_pcfx"
    ],
    "externalEmulator": ""
  },
  {
    "id": "neogeocd",
    "name": "Neo Geo CD",
    "extensions": [],
    "cores": [
      "neocd"
    ],
    "externalEmulator": ""
  },
  {
    "id": "3do",
    "name": "3DO",
    "extensions": [],
    "cores": [
      "opera"
    ],
    "externalEmulator": ""
  },
  {
    "id": "cdtv",
    "name": "Commodore CDTV",
    "extensions": [],
    "cores": [
      "puae",
      "puae2021"
    ],
    "externalEmulator": ""
  },
  {
    "id": "naomi",
    "name": "Sega Naomi",
    "extensions": [],
    "cores": [],
    "externalEmulator": "flycast"
  },
  {
    "id": "naomi2",
    "name": "Sega Naomi 2",
    "extensions": [],
    "cores": [],
    "externalEmulator": "flycast"
  },
  {
    "id": "gc",
    "name": "GameCube / Wii (Dolphin)",
    "extensions": [
      "rvz",
      "iso",
      "gcm",
      "gcz",
      "ciso",
      "wia",
      "wbfs",
      "wad"
    ],
    "cores": [],
    "externalEmulator": "dolphin"
  },
  {
    "id": "3ds",
    "name": "Nintendo 3DS (Azahar)",
    "extensions": [
      "3ds",
      "cci",
      "cxi",
      "cia",
      "3dsx"
    ],
    "cores": [],
    "externalEmulator": "azahar"
  },
  {
    "id": "nds",
    "name": "Nintendo DS (melonDS)",
    "extensions": [
      "nds",
      "dsi",
      "srl"
    ],
    "cores": [],
    "externalEmulator": "melonds"
  },
  {
    "id": "wiiu",
    "name": "Wii U (Cemu)",
    "extensions": [
      "wud",
      "wux",
      "wua",
      "rpx"
    ],
    "cores": [],
    "externalEmulator": "cemu"
  },
  {
    "id": "switch",
    "name": "Nintendo Switch (Ryujinx)",
    "extensions": [
      "nsp",
      "xci",
      "nca",
      "nro"
    ],
    "cores": [],
    "externalEmulator": "ryujinx"
  },
  {
    "id": "psp",
    "name": "PlayStation Portable (PPSSPP)",
    "extensions": [
      "cso",
      "dax",
      "prx"
    ],
    "cores": [],
    "externalEmulator": "ppsspp"
  },
  {
    "id": "psvita",
    "name": "PlayStation Vita (Vita3K)",
    "extensions": [
      "vpk"
    ],
    "cores": [],
    "externalEmulator": "vita3k"
  },
  {
    "id": "ps3",
    "name": "PlayStation 3 (RPCS3)",
    "extensions": [
      "pkg"
    ],
    "cores": [],
    "externalEmulator": "rpcs3"
  },
  {
    "id": "ps2",
    "name": "PlayStation 2 (PCSX2)",
    "extensions": [],
    "cores": [],
    "externalEmulator": "pcsx2"
  },
  {
    "id": "dreamcast",
    "name": "Dreamcast (Flycast)",
    "extensions": [
      "gdi",
      "cdi",
      "lst"
    ],
    "cores": [],
    "externalEmulator": "flycast"
  },
  {
    "id": "xbox",
    "name": "Xbox (xemu)",
    "extensions": [
      "xiso"
    ],
    "cores": [],
    "externalEmulator": "xemu"
  },
  {
    "id": "xbox360",
    "name": "Xbox 360 (Xenia)",
    "extensions": [
      "xex",
      "zar"
    ],
    "cores": [],
    "externalEmulator": "xenia"
  },
  {
    "id": "jaguar",
    "name": "Atari Jaguar / Jaguar CD (BigPEmu)",
    "extensions": [
      "j64",
      "jag",
      "abs",
      "cof"
    ],
    "cores": [],
    "externalEmulator": "bigpemu"
  }
];
